export const tagTypes = {
  auth: "Auth",
  user: "User",
  otp: "Otp",
  wishlist: "Wishlist",
  category: "Category",
  review: "Review",
  products: "Products",
  newProducts: "NewProducts",
  product: "Product",
  orders: "Orders",
  order: "Order",
  shop: "Shop",
  payment: "Payment",
  privacy_content: "privacy_content",
  about_content: "about_content",
  terms_content: "terms_content",
  refund: "Refund",
  notification: "notification",
  income: "income",
  package: "package",
  category: "category",
  subcategory: "subcategory",
  brands: "brands",
  models: "models"
};

export const tagTypesList = [
  tagTypes.auth,
  tagTypes.user,
  tagTypes.otp,
  tagTypes.wishlist,
  tagTypes.category,
  tagTypes.review,
  tagTypes.products,
  tagTypes.newProducts,
  tagTypes.product,
  tagTypes.orders,
  tagTypes.order,
  tagTypes.shop,
  tagTypes.payment,
  tagTypes.about_content,
  tagTypes.terms_content,
  tagTypes.privacy_content,
  tagTypes.refund,
  tagTypes.notification,
  tagTypes.income,
  tagTypes.package,
  tagTypes.category,
  tagTypes.subcategory,
  tagTypes.brands,
  tagTypes.models,

];
